using System.Diagnostics.CodeAnalysis;

namespace IceCreamDataBaseSignalRTest.DataTypes.Parsed.FromTwitch;

[SuppressMessage("ReSharper", "UnusedAutoPropertyAccessor.Global")]
[SuppressMessage("ReSharper", "MemberCanBePrivate.Global")]
public class IrcNotice
{
    public IrcMessage Raw { get; init; } = null!;

    /* --------------------------------------------------------------------------- */
    /* ------------------------------ Required tags ------------------------------ */
    /* --------------------------------------------------------------------------- */
    public NoticeMessageId MessageId { get; init; }

    /* --------------------------------------------------------------------------- */
    /* --------------------- Non-tag but still required data --------------------- */
    /* --------------------------------------------------------------------------- */
    public string RoomName { get; init; } = null!;
    public string Message { get; init; } = null!;
}

[SuppressMessage("ReSharper", "InconsistentNaming")]
public enum NoticeMessageId
{
    ParsingError,
    AlreadyBanned,
    AlreadyEmoteOnlyOff,
    AlreadyEmoteOnlyOn,
    AlreadyR9kOff,
    AlreadyR9kOn,
    AlreadySubsOff,
    AlreadySubsOn,
    BadBanAdmin,
    BadBanAnon,
    BadBanBroadcaster,
    BadBanGlobalMod,
    BadBanMod,
    BadBanSelf,
    BadBanStaff,
    BadCommercialError,
    BadDeleteMessageBroadcaster,
    BadDeleteMessageMod,
    BadHostError,
    BadHostHosting,
    BadHostRateExceeded,
    BadHostRejected,
    BadHostSelf,
    BadMarkerClient,
    BadModBanned,
    BadModMod,
    BadSlowDuration,
    BadTimeoutAdmin,
    BadTimeoutAnon,
    BadTimeoutBroadcaster,
    BadTimeoutDuration,
    BadTimeoutGlobalMod,
    BadTimeoutMod,
    BadTimeoutSelf,
    BadTimeoutStaff,
    BadUnbanNoBan,
    BadUnhostError,
    BadUnmodMod,
    BanSuccess,
    CmdsAvailable,
    ColorChanged,
    CommercialSuccess,
    DeleteMessageSuccess,
    EmoteOnlyOff,
    EmoteOnlyOn,
    FollowersOff,
    FollowersOn,
    FollowersOnzero,
    HostOff,
    HostOn,
    HostSuccess,
    HostSuccessViewers,
    HostTargetWentOffline,
    HostsRemaining,
    InvalidUser,
    ModSuccess,
    MsgBanned,
    MsgBadCharacters,
    MsgChannelBlocked,
    MsgChannelSuspended,
    MsgDuplicate,
    MsgEmoteonly,
    MsgFacebook,
    MsgFollowersonly,
    MsgFollowersonlyFollowed,
    MsgFollowersonlyZero,
    MsgR9k,
    MsgRatelimit,
    MsgRejected,
    MsgRejectedMandatory,
    MsgRoomNotFound,
    MsgSlowmode,
    MsgSubsonly,
    MsgSuspended,
    MsgTimedout,
    MsgVerifiedEmail,
    NoHelp,
    NoMods,
    NotHosting,
    NoPermission,
    R9kOff,
    R9kOn,
    RaidErrorAlreadyRaiding,
    RaidErrorForbidden,
    RaidErrorSelf,
    RaidErrorTooManyViewers,
    RaidErrorUnexpected,
    RaidNoticeMature,
    RaidNoticeRestrictedChat,
    RoomMods,
    SlowOff,
    SlowOn,
    SubsOff,
    SubsOn,
    TimeoutNoTimeout,
    TimeoutSuccess,
    TosBan,
    TurboOnlyColor,
    UnbanSuccess,
    UnmodSuccess,
    UnraidErrorNoActiveRaid,
    UnraidErrorUnexpected,
    UnraidSuccess,
    UnrecognizedCmd,
    UnsupportedChatroomsCmd,
    UntimeoutBanned,
    UntimeoutSuccess,
    UsageBan,
    UsageClear,
    Clear,
    UsageColor,
    UsageCommercial,
    UsageDisconnect,
    UsageEmoteOnlyOff,
    UsageEmoteOnlyOn,
    UsageFollowersOff,
    UsageFollowersOn,
    UsageHelp,
    UsageHost,
    UsageMarker,
    UsageMe,
    UsageMod,
    UsageMods,
    UsageR9kOff,
    UsageR9kOn,
    UsageRaid,
    UsageSlowOff,
    UsageSlowOn,
    UsageSubsOff,
    UsageSubsOn,
    UsageTimeout,
    UsageUnban,
    UsageUnhost,
    UsageUnmod,
    UsageUnraid,
    UsageUntimeout,
    WhisperBanned,
    WhisperBannedRecipient,
    WhisperInvalidArgs,
    WhisperInvalidLogin,
    WhisperInvalidSelf,
    WhisperLimitPerMin,
    WhisperLimitPerSec,
    WhisperRestricted,
    WhisperRestrictedRecipient
}
